[package]
name = "borrowed"
version = "0.1.0"
edition = "2021"

[dependencies]
mysql = "20.1"
tokio = { version = "1.40.0", features = ["full"] }
libloading = "0.8.5"
libc = "0.2"
db_oppration = { path = "../db_oppration" }