[package]
name = "wasm_rust"
version = "0.1.0"
edition = "2021"
authors = ["stock9host"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1

[features]
simd = []